/**
 * DTC Description Lookup — SAE J2012 / ISO 15031-6 Generic Codes
 *
 * Covers common generic P/C/B/U codes. Manufacturer-specific codes (P1xxx,
 * P3xxx, C1-3xxx, B1-3xxx, U1-3xxx) fall back to structural category info.
 */

const DTC_DATABASE: Record<string, string> = {
  // ── Camshaft / Crankshaft Position ──────────────────────────────────────
  P0010: 'Camshaft Position Actuator Circuit (Bank 1)',
  P0011: 'Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)',
  P0012: 'Camshaft Position - Timing Over-Retarded (Bank 1)',
  P0013: 'Camshaft Position Actuator Circuit, Exhaust (Bank 1)',
  P0014: 'Camshaft Position - Timing Over-Advanced or System Performance, Exhaust (Bank 1)',
  P0015: 'Camshaft Position - Timing Over-Retarded, Exhaust (Bank 1)',
  P0016: 'Crankshaft/Camshaft Position Correlation (Bank 1, Sensor A)',
  P0017: 'Crankshaft/Camshaft Position Correlation (Bank 1, Sensor B)',
  P0018: 'Crankshaft/Camshaft Position Correlation (Bank 2, Sensor A)',
  P0019: 'Crankshaft/Camshaft Position Correlation (Bank 2, Sensor B)',
  P0020: 'Camshaft Position Actuator Circuit (Bank 2)',
  P0021: 'Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)',
  P0022: 'Camshaft Position - Timing Over-Retarded (Bank 2)',
  P0023: 'Camshaft Position Actuator Circuit, Exhaust (Bank 2)',
  P0024: 'Camshaft Position - Timing Over-Advanced, Exhaust (Bank 2)',
  // ── HO2S Heater ─────────────────────────────────────────────────────────
  P0030: 'HO2S Heater Control Circuit (Bank 1, Sensor 1)',
  P0031: 'HO2S Heater Control Circuit Low (Bank 1, Sensor 1)',
  P0032: 'HO2S Heater Control Circuit High (Bank 1, Sensor 1)',
  P0036: 'HO2S Heater Control Circuit (Bank 1, Sensor 2)',
  P0037: 'HO2S Heater Control Circuit Low (Bank 1, Sensor 2)',
  P0038: 'HO2S Heater Control Circuit High (Bank 1, Sensor 2)',
  P0040: 'Upstream Oxygen Sensors Swapped (Bank 1 / Bank 2)',
  P0050: 'HO2S Heater Control Circuit (Bank 2, Sensor 1)',
  P0051: 'HO2S Heater Control Circuit Low (Bank 2, Sensor 1)',
  P0052: 'HO2S Heater Control Circuit High (Bank 2, Sensor 1)',
  P0056: 'HO2S Heater Control Circuit (Bank 2, Sensor 2)',
  P0057: 'HO2S Heater Control Circuit Low (Bank 2, Sensor 2)',
  P0058: 'HO2S Heater Control Circuit High (Bank 2, Sensor 2)',
  // ── MAF / MAP / IAT ─────────────────────────────────────────────────────
  P0068: 'MAP/MAF - Throttle Position Correlation',
  P0069: 'Manifold Absolute Pressure - Barometric Pressure Correlation',
  P0100: 'Mass or Volume Air Flow Circuit Malfunction',
  P0101: 'Mass or Volume Air Flow Circuit Range/Performance',
  P0102: 'Mass or Volume Air Flow Circuit Low Input',
  P0103: 'Mass or Volume Air Flow Circuit High Input',
  P0104: 'Mass or Volume Air Flow Circuit Intermittent',
  P0105: 'Manifold Absolute Pressure/Barometric Pressure Circuit Malfunction',
  P0106: 'MAP/Barometric Pressure Circuit Range/Performance',
  P0107: 'MAP/Barometric Pressure Circuit Low Input',
  P0108: 'MAP/Barometric Pressure Circuit High Input',
  P0109: 'MAP/Barometric Pressure Circuit Intermittent',
  P0110: 'Intake Air Temperature Circuit Malfunction',
  P0111: 'Intake Air Temperature Circuit Range/Performance',
  P0112: 'Intake Air Temperature Circuit Low Input',
  P0113: 'Intake Air Temperature Circuit High Input',
  P0114: 'Intake Air Temperature Circuit Intermittent',
  // ── Engine Coolant Temperature ───────────────────────────────────────────
  P0115: 'Engine Coolant Temperature Circuit Malfunction',
  P0116: 'Engine Coolant Temperature Circuit Range/Performance',
  P0117: 'Engine Coolant Temperature Circuit Low Input',
  P0118: 'Engine Coolant Temperature Circuit High Input',
  P0119: 'Engine Coolant Temperature Circuit Intermittent',
  P0125: 'Insufficient Coolant Temperature for Closed-Loop Fuel Control',
  P0128: 'Coolant Thermostat - Coolant Temperature Below Regulating Temperature',
  // ── O2 Sensors ──────────────────────────────────────────────────────────
  P0130: 'O2 Sensor Circuit Malfunction (Bank 1, Sensor 1)',
  P0131: 'O2 Sensor Circuit Low Voltage (Bank 1, Sensor 1)',
  P0132: 'O2 Sensor Circuit High Voltage (Bank 1, Sensor 1)',
  P0133: 'O2 Sensor Circuit Slow Response (Bank 1, Sensor 1)',
  P0134: 'O2 Sensor Circuit No Activity Detected (Bank 1, Sensor 1)',
  P0135: 'O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 1)',
  P0136: 'O2 Sensor Circuit Malfunction (Bank 1, Sensor 2)',
  P0137: 'O2 Sensor Circuit Low Voltage (Bank 1, Sensor 2)',
  P0138: 'O2 Sensor Circuit High Voltage (Bank 1, Sensor 2)',
  P0139: 'O2 Sensor Circuit Slow Response (Bank 1, Sensor 2)',
  P0140: 'O2 Sensor Circuit No Activity Detected (Bank 1, Sensor 2)',
  P0141: 'O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 2)',
  P0150: 'O2 Sensor Circuit Malfunction (Bank 2, Sensor 1)',
  P0151: 'O2 Sensor Circuit Low Voltage (Bank 2, Sensor 1)',
  P0152: 'O2 Sensor Circuit High Voltage (Bank 2, Sensor 1)',
  P0153: 'O2 Sensor Circuit Slow Response (Bank 2, Sensor 1)',
  P0154: 'O2 Sensor Circuit No Activity Detected (Bank 2, Sensor 1)',
  P0155: 'O2 Sensor Heater Circuit Malfunction (Bank 2, Sensor 1)',
  P0156: 'O2 Sensor Circuit Malfunction (Bank 2, Sensor 2)',
  P0157: 'O2 Sensor Circuit Low Voltage (Bank 2, Sensor 2)',
  P0158: 'O2 Sensor Circuit High Voltage (Bank 2, Sensor 2)',
  P0159: 'O2 Sensor Circuit Slow Response (Bank 2, Sensor 2)',
  P0160: 'O2 Sensor Circuit No Activity Detected (Bank 2, Sensor 2)',
  P0161: 'O2 Sensor Heater Circuit Malfunction (Bank 2, Sensor 2)',
  // ── Fuel Trim ───────────────────────────────────────────────────────────
  P0170: 'Fuel Trim Malfunction (Bank 1)',
  P0171: 'System Too Lean (Bank 1)',
  P0172: 'System Too Rich (Bank 1)',
  P0173: 'Fuel Trim Malfunction (Bank 2)',
  P0174: 'System Too Lean (Bank 2)',
  P0175: 'System Too Rich (Bank 2)',
  // ── Fuel Injectors ──────────────────────────────────────────────────────
  P0200: 'Injector Circuit Malfunction',
  P0201: 'Injector Circuit Malfunction - Cylinder 1',
  P0202: 'Injector Circuit Malfunction - Cylinder 2',
  P0203: 'Injector Circuit Malfunction - Cylinder 3',
  P0204: 'Injector Circuit Malfunction - Cylinder 4',
  P0205: 'Injector Circuit Malfunction - Cylinder 5',
  P0206: 'Injector Circuit Malfunction - Cylinder 6',
  P0207: 'Injector Circuit Malfunction - Cylinder 7',
  P0208: 'Injector Circuit Malfunction - Cylinder 8',
  P0261: 'Cylinder 1 Injector Circuit Low',
  P0262: 'Cylinder 1 Injector Circuit High',
  P0264: 'Cylinder 2 Injector Circuit Low',
  P0265: 'Cylinder 2 Injector Circuit High',
  P0267: 'Cylinder 3 Injector Circuit Low',
  P0268: 'Cylinder 3 Injector Circuit High',
  P0270: 'Cylinder 4 Injector Circuit Low',
  P0271: 'Cylinder 4 Injector Circuit High',
  P0273: 'Cylinder 5 Injector Circuit Low',
  P0274: 'Cylinder 5 Injector Circuit High',
  P0276: 'Cylinder 6 Injector Circuit Low',
  P0277: 'Cylinder 6 Injector Circuit High',
  // ── Misfire ─────────────────────────────────────────────────────────────
  P0300: 'Random/Multiple Cylinder Misfire Detected',
  P0301: 'Cylinder 1 Misfire Detected',
  P0302: 'Cylinder 2 Misfire Detected',
  P0303: 'Cylinder 3 Misfire Detected',
  P0304: 'Cylinder 4 Misfire Detected',
  P0305: 'Cylinder 5 Misfire Detected',
  P0306: 'Cylinder 6 Misfire Detected',
  P0307: 'Cylinder 7 Misfire Detected',
  P0308: 'Cylinder 8 Misfire Detected',
  P0309: 'Cylinder 9 Misfire Detected',
  P0310: 'Cylinder 10 Misfire Detected',
  P0311: 'Cylinder 11 Misfire Detected',
  P0312: 'Cylinder 12 Misfire Detected',
  P0313: 'Misfire Detected with Low Fuel',
  P0315: 'Crankshaft Position System Variation Not Learned',
  // ── Knock Sensor ────────────────────────────────────────────────────────
  P0325: 'Knock Sensor 1 Circuit Malfunction (Bank 1)',
  P0326: 'Knock Sensor 1 Circuit Range/Performance (Bank 1)',
  P0327: 'Knock Sensor 1 Circuit Low Input (Bank 1)',
  P0328: 'Knock Sensor 1 Circuit High Input (Bank 1)',
  P0329: 'Knock Sensor 1 Circuit Intermittent (Bank 1)',
  P0330: 'Knock Sensor 2 Circuit Malfunction (Bank 2)',
  P0331: 'Knock Sensor 2 Circuit Range/Performance (Bank 2)',
  P0332: 'Knock Sensor 2 Circuit Low Input (Bank 2)',
  P0333: 'Knock Sensor 2 Circuit High Input (Bank 2)',
  // ── Crankshaft / Camshaft Position Sensors ──────────────────────────────
  P0335: 'Crankshaft Position Sensor A Circuit Malfunction',
  P0336: 'Crankshaft Position Sensor A Circuit Range/Performance',
  P0337: 'Crankshaft Position Sensor A Circuit Low Input',
  P0338: 'Crankshaft Position Sensor A Circuit High Input',
  P0339: 'Crankshaft Position Sensor A Circuit Intermittent',
  P0340: 'Camshaft Position Sensor Circuit Malfunction (Bank 1, Sensor A)',
  P0341: 'Camshaft Position Sensor Circuit Range/Performance (Bank 1, Sensor A)',
  P0342: 'Camshaft Position Sensor Circuit Low Input (Bank 1, Sensor A)',
  P0343: 'Camshaft Position Sensor Circuit High Input (Bank 1, Sensor A)',
  P0344: 'Camshaft Position Sensor Circuit Intermittent (Bank 1, Sensor A)',
  P0345: 'Camshaft Position Sensor Circuit (Bank 2, Sensor A)',
  P0365: 'Camshaft Position Sensor B Circuit (Bank 1)',
  P0390: 'Camshaft Position Sensor B Circuit (Bank 2)',
  // ── Ignition Coil ───────────────────────────────────────────────────────
  P0350: 'Ignition Coil Primary/Secondary Circuit Malfunction',
  P0351: 'Ignition Coil A Primary/Secondary Circuit Malfunction',
  P0352: 'Ignition Coil B Primary/Secondary Circuit Malfunction',
  P0353: 'Ignition Coil C Primary/Secondary Circuit Malfunction',
  P0354: 'Ignition Coil D Primary/Secondary Circuit Malfunction',
  P0355: 'Ignition Coil E Primary/Secondary Circuit Malfunction',
  P0356: 'Ignition Coil F Primary/Secondary Circuit Malfunction',
  P0357: 'Ignition Coil G Primary/Secondary Circuit Malfunction',
  P0358: 'Ignition Coil H Primary/Secondary Circuit Malfunction',
  // ── EGR ─────────────────────────────────────────────────────────────────
  P0400: 'Exhaust Gas Recirculation Flow Malfunction',
  P0401: 'Exhaust Gas Recirculation Flow Insufficient Detected',
  P0402: 'Exhaust Gas Recirculation Flow Excessive Detected',
  P0403: 'Exhaust Gas Recirculation Circuit Malfunction',
  P0404: 'Exhaust Gas Recirculation Circuit Range/Performance',
  P0405: 'Exhaust Gas Recirculation Sensor A Circuit Low',
  P0406: 'Exhaust Gas Recirculation Sensor A Circuit High',
  P0407: 'Exhaust Gas Recirculation Sensor B Circuit Low',
  P0408: 'Exhaust Gas Recirculation Sensor B Circuit High',
  // ── Secondary Air Injection ──────────────────────────────────────────────
  P0410: 'Secondary Air Injection System Malfunction',
  P0411: 'Secondary Air Injection System Incorrect Flow Detected',
  P0412: 'Secondary Air Injection System Switching Valve A Circuit Malfunction',
  P0413: 'Secondary Air Injection System Switching Valve A Circuit Open',
  P0414: 'Secondary Air Injection System Switching Valve A Circuit Shorted',
  // ── Catalyst System ──────────────────────────────────────────────────────
  P0420: 'Catalyst System Efficiency Below Threshold (Bank 1)',
  P0421: 'Warm Up Catalyst Efficiency Below Threshold (Bank 1)',
  P0422: 'Main Catalyst Efficiency Below Threshold (Bank 1)',
  P0423: 'Heated Catalyst Efficiency Below Threshold (Bank 1)',
  P0430: 'Catalyst System Efficiency Below Threshold (Bank 2)',
  P0431: 'Warm Up Catalyst Efficiency Below Threshold (Bank 2)',
  P0432: 'Main Catalyst Efficiency Below Threshold (Bank 2)',
  // ── EVAP ─────────────────────────────────────────────────────────────────
  P0440: 'Evaporative Emission Control System Malfunction',
  P0441: 'Evaporative Emission Control System Incorrect Purge Flow',
  P0442: 'EVAP System Leak Detected (Small Leak)',
  P0443: 'EVAP Purge Control Valve Circuit Malfunction',
  P0444: 'EVAP Purge Control Valve Circuit Open',
  P0445: 'EVAP Purge Control Valve Circuit Shorted',
  P0446: 'EVAP Vent Control Circuit Malfunction',
  P0447: 'EVAP Vent Control Circuit Open',
  P0448: 'EVAP Vent Control Circuit Shorted',
  P0449: 'EVAP Vent Valve/Solenoid Circuit Malfunction',
  P0450: 'EVAP Pressure Sensor Malfunction',
  P0451: 'EVAP Pressure Sensor Range/Performance',
  P0452: 'EVAP Pressure Sensor Low Input',
  P0453: 'EVAP Pressure Sensor High Input',
  P0455: 'EVAP System Leak Detected (Large Leak)',
  P0456: 'EVAP System Leak Detected (Very Small Leak)',
  P0457: 'EVAP System Leak Detected (Fuel Cap Loose/Off)',
  P0458: 'EVAP Purge Control Valve Circuit Low',
  P0459: 'EVAP Purge Control Valve Circuit High',
  // ── Fuel Level ───────────────────────────────────────────────────────────
  P0460: 'Fuel Level Sensor Circuit Malfunction',
  P0461: 'Fuel Level Sensor Circuit Range/Performance',
  P0462: 'Fuel Level Sensor Circuit Low Input',
  P0463: 'Fuel Level Sensor Circuit High Input',
  // ── VSS / Idle Control ───────────────────────────────────────────────────
  P0500: 'Vehicle Speed Sensor Malfunction',
  P0501: 'Vehicle Speed Sensor Range/Performance',
  P0502: 'Vehicle Speed Sensor Circuit Low Input',
  P0503: 'Vehicle Speed Sensor Intermittent/Erratic/High',
  P0505: 'Idle Control System Malfunction',
  P0506: 'Idle Control System RPM Lower Than Expected',
  P0507: 'Idle Control System RPM Higher Than Expected',
  // ── Engine Oil Pressure ──────────────────────────────────────────────────
  P0520: 'Engine Oil Pressure Sensor/Switch Circuit Malfunction',
  P0521: 'Engine Oil Pressure Sensor/Switch Range/Performance',
  P0522: 'Engine Oil Pressure Sensor/Switch Low Voltage',
  P0523: 'Engine Oil Pressure Sensor/Switch High Voltage',
  // ── System Voltage ───────────────────────────────────────────────────────
  P0560: 'System Voltage Malfunction',
  P0562: 'System Voltage Low',
  P0563: 'System Voltage High',
  // ── ECM / Computer Output ────────────────────────────────────────────────
  P0600: 'Serial Communication Link Malfunction',
  P0601: 'Internal Control Module Memory Check Sum Error',
  P0602: 'Control Module Programming Error',
  P0603: 'Internal Control Module KAM Error',
  P0604: 'Internal Control Module RAM Error',
  P0605: 'Internal Control Module ROM Error',
  P0606: 'Control Module Processor Fault',
  P0607: 'Control Module Performance',
  P0610: 'Control Module Vehicle Options Error',
  P0620: 'Generator Control Circuit Malfunction',
  P0622: 'Generator Field F Terminal Circuit Malfunction',
  P0627: 'Fuel Pump A Control Circuit Open',
  P0628: 'Fuel Pump A Control Circuit Low',
  P0629: 'Fuel Pump A Control Circuit High',
  P0650: 'Malfunction Indicator Lamp (MIL) Control Circuit Malfunction',
  // ── Transmission ─────────────────────────────────────────────────────────
  P0700: 'Transmission Control System Malfunction',
  P0701: 'Transmission Control System Range/Performance',
  P0702: 'Transmission Control System Electrical',
  P0705: 'Transmission Range Sensor Circuit Malfunction (PRNDL)',
  P0706: 'Transmission Range Sensor Circuit Range/Performance',
  P0707: 'Transmission Range Sensor Circuit Low Input',
  P0708: 'Transmission Range Sensor Circuit High Input',
  P0710: 'Transmission Fluid Temperature Sensor Circuit Malfunction',
  P0711: 'Transmission Fluid Temperature Sensor Circuit Range/Performance',
  P0712: 'Transmission Fluid Temperature Sensor Circuit Low Input',
  P0713: 'Transmission Fluid Temperature Sensor Circuit High Input',
  P0715: 'Input/Turbine Speed Sensor Circuit Malfunction',
  P0716: 'Input/Turbine Speed Sensor Circuit Range/Performance',
  P0717: 'Input/Turbine Speed Sensor Circuit No Signal',
  P0720: 'Output Speed Sensor Circuit Malfunction',
  P0721: 'Output Speed Sensor Circuit Range/Performance',
  P0722: 'Output Speed Sensor Circuit No Signal',
  P0730: 'Incorrect Gear Ratio',
  P0731: 'Gear 1 Incorrect Ratio',
  P0732: 'Gear 2 Incorrect Ratio',
  P0733: 'Gear 3 Incorrect Ratio',
  P0734: 'Gear 4 Incorrect Ratio',
  P0735: 'Gear 5 Incorrect Ratio',
  P0736: 'Reverse Incorrect Ratio',
  P0740: 'Torque Converter Clutch Circuit Malfunction',
  P0741: 'Torque Converter Clutch Circuit Performance or Stuck Off',
  P0742: 'Torque Converter Clutch Circuit Stuck On',
  P0743: 'Torque Converter Clutch Circuit Electrical',
  P0748: 'Pressure Control Solenoid A Electrical',
  P0750: 'Shift Solenoid A Malfunction',
  P0751: 'Shift Solenoid A Performance or Stuck Off',
  P0752: 'Shift Solenoid A Stuck On',
  P0753: 'Shift Solenoid A Electrical',
  P0755: 'Shift Solenoid B Malfunction',
  P0756: 'Shift Solenoid B Performance or Stuck Off',
  P0757: 'Shift Solenoid B Stuck On',
  P0758: 'Shift Solenoid B Electrical',
  P0760: 'Shift Solenoid C Malfunction',
  P0761: 'Shift Solenoid C Performance or Stuck Off',
  P0762: 'Shift Solenoid C Stuck On',
  P0763: 'Shift Solenoid C Electrical',
  P0765: 'Shift Solenoid D Malfunction',
  P0780: 'Shift Malfunction',
  P0781: '1-2 Shift Malfunction',
  P0782: '2-3 Shift Malfunction',
  P0783: '3-4 Shift Malfunction',
  P0784: '4-5 Shift Malfunction',
  // ── Common P2 (Standardized) ─────────────────────────────────────────────
  P2096: 'Post-Catalyst Fuel Trim System Too Lean (Bank 1)',
  P2097: 'Post-Catalyst Fuel Trim System Too Rich (Bank 1)',
  P2098: 'Post-Catalyst Fuel Trim System Too Lean (Bank 2)',
  P2099: 'Post-Catalyst Fuel Trim System Too Rich (Bank 2)',
  P2100: 'Throttle Actuator Control Motor Circuit Open',
  P2101: 'Throttle Actuator Control Motor Circuit Range/Performance',
  P2102: 'Throttle Actuator Control Motor Circuit Low',
  P2103: 'Throttle Actuator Control Motor Circuit High',
  P2104: 'Throttle Actuator Control System - Forced Idle',
  P2105: 'Throttle Actuator Control System - Forced Engine Shutdown',
  P2106: 'Throttle Actuator Control System - Forced Limited Power',
  P2107: 'Throttle Actuator Control Module Processor',
  P2110: 'Throttle Actuator Control System - Forced Limited RPM',
  P2111: 'Throttle Actuator Control System - Stuck Open',
  P2112: 'Throttle Actuator Control System - Stuck Closed',
  P2122: 'Throttle/Pedal Position Sensor D Circuit Low',
  P2123: 'Throttle/Pedal Position Sensor D Circuit High',
  P2127: 'Throttle/Pedal Position Sensor E Circuit Low',
  P2128: 'Throttle/Pedal Position Sensor E Circuit High',
  P2135: 'Throttle/Pedal Position Sensor A/B Voltage Correlation',
  P2138: 'Throttle/Pedal Position Sensor D/E Voltage Correlation',
  P2176: 'Throttle Actuator Control System - Idle Position Not Learned',
  P2187: 'System Too Lean at Idle (Bank 1)',
  P2188: 'System Too Rich at Idle (Bank 1)',
  P2191: 'System Too Lean at Higher Load (Bank 1)',
  P2192: 'System Too Rich at Higher Load (Bank 1)',
  P2195: 'O2 Sensor Signal Stuck Lean (Bank 1, Sensor 1)',
  P2196: 'O2 Sensor Signal Stuck Rich (Bank 1, Sensor 1)',
  P2228: 'Barometric Pressure Circuit Low Input',
  P2229: 'Barometric Pressure Circuit High Input',
  P2270: 'O2 Sensor Signal Stuck Lean (Bank 1, Sensor 2)',
  P2271: 'O2 Sensor Signal Stuck Rich (Bank 1, Sensor 2)',
  // ── Common Network/CAN (U0) ───────────────────────────────────────────────
  U0001: 'High Speed CAN Communication Bus',
  U0002: 'High Speed CAN Communication Bus Performance',
  U0003: 'High Speed CAN Communication Bus Open',
  U0004: 'High Speed CAN Communication Bus Short to Battery',
  U0005: 'High Speed CAN Communication Bus Short to Ground',
  U0010: 'Medium Speed CAN Communication Bus',
  U0020: 'Low Speed CAN Communication Bus',
  U0100: 'Lost Communication With ECM/PCM',
  U0101: 'Lost Communication With TCM',
  U0102: 'Lost Communication With Transfer Case Control Module',
  U0104: 'Lost Communication With Cruise Control Module',
  U0107: 'Lost Communication With Throttle Actuator Control Module',
  U0109: 'Lost Communication With Fuel Pump Control Module',
  U0110: 'Lost Communication With Drive Motor Control Module',
  U0121: 'Lost Communication With ABS Control Module',
  U0122: 'Lost Communication With Vehicle Dynamics Control Module',
  U0123: 'Lost Communication With Yaw Rate Sensor Module',
  U0126: 'Lost Communication With Steering Angle Sensor Module',
  U0127: 'Lost Communication With Tire Pressure Monitor Module',
  U0129: 'Lost Communication With Brake System Control Module',
  U0131: 'Lost Communication With Power Steering Control Module',
  U0140: 'Lost Communication With Body Control Module',
  U0141: 'Lost Communication With Body Control Module A',
  U0142: 'Lost Communication With Body Control Module B',
  U0151: 'Lost Communication With Restraints Control Module',
  U0155: 'Lost Communication With Instrument Panel Cluster',
  U0164: 'Lost Communication With HVAC Control Module',
  U0168: 'Lost Communication With Vehicle Immobilizer Control Module',
  U0184: 'Lost Communication With Radio',
  U0197: 'Lost Communication With Telephone Control Module',
  U0198: 'Lost Communication With Telematics Control Module',
  // ── Common Chassis (C0) ───────────────────────────────────────────────────
  C0035: 'Left Front Wheel Speed Sensor Circuit',
  C0036: 'Left Front Wheel Speed Sensor Circuit Range/Performance',
  C0040: 'Right Front Wheel Speed Sensor Circuit',
  C0041: 'Right Front Wheel Speed Sensor Circuit Range/Performance',
  C0045: 'Left Rear Wheel Speed Sensor Circuit',
  C0046: 'Left Rear Wheel Speed Sensor Circuit Range/Performance',
  C0050: 'Right Rear Wheel Speed Sensor Circuit',
  C0051: 'Right Rear Wheel Speed Sensor Circuit Range/Performance',
  C0060: 'Left Front ABS Solenoid Circuit',
  C0065: 'Right Front ABS Solenoid Circuit',
  C0070: 'Left Rear ABS Solenoid Circuit',
  C0075: 'Right Rear ABS Solenoid Circuit',
  C0110: 'ABS Motor Circuit',
  C0121: 'ABS Valve Relay Circuit',
  C0161: 'ABS/TCS Brake Switch Circuit',
  C0196: 'Yaw Rate Sensor Circuit',
  C0242: 'PCM Indicated TCS Fault',
  C0265: 'EBCM Relay Circuit',
  C0268: 'Pump Motor Circuit Open/Short to Battery',
}

// ── Structural fallback: category from code structure ────────────────────────

const P_SUBCATEGORIES: Record<number, string> = {
  0: 'Fuel Volume Regulator',
  1: 'Fuel & Air Metering',
  2: 'Fuel & Air Metering / Injector Circuit',
  3: 'Ignition System / Misfire',
  4: 'Auxiliary Emission Controls',
  5: 'Speed / Idle / Gear Control',
  6: 'Computer & Auxiliary Outputs',
  7: 'Transmission',
  8: 'Transmission / Hybrid Drive',
  9: 'User Defined',
}

function dtcCategory(code: string): string {
  if (code.length < 5) return 'Unknown System'
  const sys = code[0].toUpperCase()
  const d1 = parseInt(code[1]) // 0/2 = SAE generic, 1/3 = mfr specific
  const d2 = parseInt(code[2])
  const specificity = (d1 === 0 || d1 === 2) ? 'Generic' : 'Manufacturer Specific'
  const sysNames: Record<string, string> = { P: 'Powertrain', C: 'Chassis', B: 'Body', U: 'Network' }
  const sysName = sysNames[sys] ?? sys

  if (sys === 'P' && (d1 === 0 || d1 === 2)) {
    const sub = P_SUBCATEGORIES[d2] ?? 'Unknown Subsystem'
    return `${sysName} — ${specificity} — ${sub}`
  }
  return `${sysName} — ${specificity}`
}

/** Look up a description for a DTC code. Returns undefined for unknown codes. */
export function describeDtc(code: string): string {
  const upper = code.toUpperCase()
  return DTC_DATABASE[upper] ?? dtcCategory(upper)
}
